#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v10
# autospec commit: 6fa3d52db448
#
Name     : usrsctp
Version  : 0.9.5.0
Release  : 1
URL      : https://github.com/sctplab/usrsctp/archive/0.9.5.0/usrsctp-0.9.5.0.tar.gz
Source0  : https://github.com/sctplab/usrsctp/archive/0.9.5.0/usrsctp-0.9.5.0.tar.gz
Summary  : SCTP implementation
Group    : Development/Tools
License  : BSD-3-Clause
Requires: usrsctp-lib = %{version}-%{release}
Requires: usrsctp-license = %{version}-%{release}
BuildRequires : buildreq-meson
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# usrsctp
[![Coverity Scan Build Status](https://scan.coverity.com/projects/13430/badge.svg)](https://scan.coverity.com/projects/usrsctp)

%package dev
Summary: dev components for the usrsctp package.
Group: Development
Requires: usrsctp-lib = %{version}-%{release}
Provides: usrsctp-devel = %{version}-%{release}
Requires: usrsctp = %{version}-%{release}

%description dev
dev components for the usrsctp package.


%package lib
Summary: lib components for the usrsctp package.
Group: Libraries
Requires: usrsctp-license = %{version}-%{release}

%description lib
lib components for the usrsctp package.


%package license
Summary: license components for the usrsctp package.
Group: Default

%description license
license components for the usrsctp package.


%prep
%setup -q -n usrsctp-0.9.5.0
cd %{_builddir}/usrsctp-0.9.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1716938938
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/usrsctp
cp %{_builddir}/usrsctp-%{version}/LICENSE.md %{buildroot}/usr/share/package-licenses/usrsctp/065e53e772f604ccf39b435c4bc791d942279064 || :
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/usrsctp.h
/usr/lib64/libusrsctp.so
/usr/lib64/pkgconfig/usrsctp.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libusrsctp.so.2
/usr/lib64/libusrsctp.so.2.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/usrsctp/065e53e772f604ccf39b435c4bc791d942279064
